### ISSUE TITLE
elasticsearch failes to start

### ISSUE THREAD

**Issue by clemenko** [ahromis/swarm-elk#1]
Docker 1.13-cs1-rc1
UCP 2.1.0-beta1

vm.max_map_count was updated.
```
[root@beta-c105 ~]# sysctl -p
vm.max_map_count = 262144
```

From the logs : 
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 1973026816 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /tmp/hs_err_pid1.log
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x000000008a660000, 1973026816, 0) failed; error='Cannot allocate memory' (errno=12)
```

**Comment by ahromis** [comment]
@clemenko it looks like this is related to the ES heap size. I was able to reproduce by setting these values `ES_JAVA_OPTS: -Xms2g -Xmx2g` in the compose file to greater than the physical memory on the machine. Try increasing the memory on your host machine or decreasing the ES heap size.

**Comment by clemenko** [comment]
AH, makes sense. I build my vms with 2gb of ram.
