### ISSUE TITLE
Issue building Index

### ISSUE THREAD

**Issue by Berndinox** [ahromis/swarm-elk#2]
First of all thanks for the time spent on building the compose. **Good Work.**

However i'm not able to build the index with that command:
`docker run -dit --log-driver=gelf --log-opt gelf-address=udp://<logstash-host>:12201 alpine ping 8.8.8.8`
i do also try:
`docker run -dit --log-driver=gelf --log-opt gelf-address=udp://<logstash-host>:12201 alpine logger error`

after i telnet on-to the logstach on port 10514 and send some strange keys, i was able to build the index.

any ideas?

**Comment by ahromis** [comment]
Hi @Berndinox, thanks for the input!

I might have had a typo in that command, I just updated it without the `-d` flag since using `-d` with `-it` won't work.

I just confirmed it worked on my machine. You should see something like this in the logstash logs while the ping is running.

```
{
       "source_host" => "10.255.0.3",
             "level" => 6,
           "created" => "2017-02-27T22:41:01.670076264Z",
           "message" => "64 bytes from 8.8.8.8: seq=0 ttl=61 time=24.529 ms",
           "version" => "1.1",
           "command" => "ping 8.8.8.8",
        "image_name" => "alpine",
        "@timestamp" => 2017-02-27T22:41:02.020Z,
    "container_name" => "eager_kowalevski",
              "host" => "manager",
          "@version" => "1",
               "tag" => "b3bc46393fea",
          "image_id" => "sha256:88e169ea8f46ff0d0df784b1b254a15ecfaf045aee1856dca1ec242fdd231ddd",
      "container_id" => "b3bc46393fea562d0847d2f5cd577b625a4b521ea108fc5f44becdea28ddf41e"
}
```

Let me know if you're still running into issues.

**Comment by Berndinox** [comment]
Thanks! Looks good
