### ISSUE TITLE
Elasticsearch cluster health is not a good healthcheck for tasks

### ISSUE THREAD

**Issue by jdharmon** [ahromis/swarm-elk#4]
The ```/_cluster/health``` API call gives you the health of the cluster, not the individual node. If you lose a node in the cluster, calls to ```/_cluster/health``` on the healthy nodes will return ```status: yellow```, which can lead to healthy tasks being killed.

**Comment by ahromis** [comment]
Thanks for pointing that out, @jdharmon . I removed the ES healthcheck since I was hoping `local=true` would be on a per-node basis. I would rather rely on the exit status of the container than the healthcheck. Closing out this issue.
